#!/usr/bin/env python3
"""
Measure the one-year outcome of the point-in-time backtest (PIT-1).

Idempotent — safe to re-run. For each ``synthetic_recommendation`` row whose
horizon (cutoff + 1 year) has passed and that is not final yet, it prices the
ticker and ``TRACK_RECORD.benchmark`` at both ends and writes the return, the
benchmark's return and the excess — or marks why it could not
(``analysis/synthetic_outcome.py``). Rows are generated by
``scripts/point_in_time_backtest.py``.

Run from project root:
    ./venv/bin/python3 scripts/score_synthetic_outcomes.py
"""

import sys
from pathlib import Path

_sys_root = Path(__file__).resolve().parent.parent
if str(_sys_root) not in sys.path:
    sys.path.insert(0, str(_sys_root))
from bootstrap import ensure_project_root

ensure_project_root()

from loguru import logger

from analysis.synthetic_backtest import synthetic_backtest_store
from analysis.synthetic_outcome import score_due_outcomes


def main() -> int:
    """Exit 1 only when nothing could be written at all: the outcome columns
    are not confirmed present (same refusal as ``point_in_time_backtest.py``).
    A row without history or delisted is an outcome, not a failure of the run.
    """
    store = synthetic_backtest_store
    if not store.outcome_columns_verified:
        store.outcome_columns_verified = store._migrate_outcome_columns(store._engine)
    if not store.outcome_columns_verified:
        logger.error("synthetic_outcome: outcome columns not verified — refusing to score")
        return 1

    logger.info("synthetic_outcome: starting scoring run")
    result = score_due_outcomes(store)
    logger.info("synthetic_outcome: done — " + " ".join(f"{k}={v}" for k, v in result.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
